capstone project -Module 1 - Ceremony page
yashodhicy/JCRPictures pull request #6
Opened 2023-04-19 16:58 UTC by yashodhicy

1. title - JCR Award ceremony
2. mobile version
3. desktop version
4. dynamic section of nominees
5. loom introduction video
6. updated readme file

Extra feature 

- The see more button to the mobile version and can see the rest of the nominated celebrities

2023-04-19 19:07 UTC, huseyinbiyik requested changes
Hi @yashodhicy 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- JavaScript codes are DRY 👍 
- Linter set up well and checks pass 🟢
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝

## Required Changes ♻️
- Kindly add an alt attribute to each img element on your project, you have alt attribute only on your logo image. Alt attributes are important in terms of accessibility. You can check this link to learn more: https://en.wikipedia.org/wiki/Alt_attribute#:~:text=The%20alt%20attribute%20is%20the,element%20that%20cannot%20be%20rendered. 

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML" 


_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 19:07 UTC, huseyinbiyik commented on README.md
> +- https://yashodhicy.github.io/JCRPictures
Great job adding the live demo of your project 👍  But let's make sure everything is deployed properly and working fine. On the Github Pages settings, you can find a setting to change the branch for the deployment ☁️ Currently your live page looks like the below ꝇ
<img width="1439" alt="Screenshot 2023-04-19 at 8 17 25 PM" src="https://user-images.githubusercontent.com/25887253/233151906-6fd32005-892a-40ef-a06e-8bda2dbd375b.png">

2023-04-19 19:07 UTC, huseyinbiyik commented on style.css
> +/* stylelint-disable no-descending-specificity */
Please don't disable linters.
There are a few reasons for using linters:
Catching syntax errors is more efficient. There is no need to debug simple mistakes like typos - the linter does it for you.
The entire codebase looks like written by one person.
Programmers can focus on solving problems, instead of cleaning up the code.

You can solve 'descending specificity' errors by changing the places of the CSS declarations in this file or giving more specific ids to the elements 👍

2023-04-19 19:07 UTC, huseyinbiyik commented on style.css
>  #mobile-menu {
Great job with your logo, your page looks dynamic 🧨 But let's follow the design guideline and make the mobile nav area transparent instead of a fixed white area, so the background image can be visible. 
<img width="808" alt="Screenshot 2023-04-19 at 8 23 47 PM" src="https://user-images.githubusercontent.com/25887253/233154649-778b7561-2051-4731-af2b-50d41916cac4.png">
<img width="396" alt="Screenshot 2023-04-19 at 8 24 56 PM" src="https://user-images.githubusercontent.com/25887253/233154656-5b74f52f-3f46-4412-bd86-75ab383de575.png">

2023-04-19 19:07 UTC, huseyinbiyik commented on index.html
> +            <a href="index.html"><img class="logo" alt="logo" src="images/JCR.gif" loop="infinite"></a>
Please follow the design guideline and add the gray navigation bar with all links on the design for both pages (index and about page). 👍 We should stick to the design guideline for this project. 
<img width="1440" alt="Screenshot 2023-04-19 at 8 33 40 PM" src="https://user-images.githubusercontent.com/25887253/233155919-ed50a99a-e95f-4dc8-81a3-8ba672ddd9d3.png">
<img width="1231" alt="Screenshot 2023-04-19 at 8 34 22 PM" src="https://user-images.githubusercontent.com/25887253/233155933-5b0406d3-5d54-4454-b0de-222797ce69e6.png">

2023-04-19 19:07 UTC, huseyinbiyik commented on style.css
> +  }
<img width="1231" alt="Screenshot 2023-04-19 at 8 40 19 PM" src="https://user-images.githubusercontent.com/25887253/233156699-8b92eec6-8e81-4498-8027-f9b73b123da6.png">
<img width="1438" alt="Screenshot 2023-04-19 at 8 40 32 PM" src="https://user-images.githubusercontent.com/25887253/233156706-4ae18e60-72f5-4a07-ab95-8a9c405adc96.png">

- [ ] Great job aligning your logo to the left 👍  But let's align all links to the right, not to the middle. 👉

<img width="1438" alt="Screenshot 2023-04-19 at 8 45 36 PM" src="https://user-images.githubusercontent.com/25887253/233158407-9c385e6a-98d1-477e-9211-22be809249b2.png">

- [ ] There should be an equal amount of space around the menu according to the design guideline, there is less space on the right than left on your implementation. Kindly make sure they are equal 👍

2023-04-19 19:07 UTC, huseyinbiyik commented on index.html
>  <footer>
Great job with adding a footer to the desktop version 🖥️  Kindly add a footer to your mobile version. 
<img width="473" alt="Screenshot 2023-04-19 at 8 56 01 PM" src="https://user-images.githubusercontent.com/25887253/233160001-45e08294-3e74-47ca-a7e8-0b6f31fa1b35.png">

2023-04-19 19:07 UTC, huseyinbiyik commented on style.css
>  #namelist {
Please make sure you added space around the nominees section and add the chessboard decoration image to the back of each photo like on the design guideline. 
<img width="1440" alt="Screenshot 2023-04-19 at 9 20 08 PM" src="https://user-images.githubusercontent.com/25887253/233166004-434cfcb7-7511-423d-b95e-1aae872a2d87.png">

<img width="1206" alt="Screenshot 2023-04-19 at 9 19 49 PM" src="https://user-images.githubusercontent.com/25887253/233165985-63332b7c-b8e5-46c7-882a-c68d59036f34.png">

2023-04-19 19:07 UTC, huseyinbiyik commented on about.html
>      <section id="introduction" class="aboutintroduction">
Kindly add this gray separator between the sections like on the design guideline.
<img width="924" alt="Screenshot 2023-04-19 at 9 36 38 PM" src="https://user-images.githubusercontent.com/25887253/233169192-cad98305-8772-4c9c-aaf2-c510e35a5ecc.png">
<img width="1440" alt="Screenshot 2023-04-19 at 9 37 10 PM" src="https://user-images.githubusercontent.com/25887253/233169203-3a77036f-4477-421c-9ba4-cec0730c128b.png">

2023-04-19 19:07 UTC, huseyinbiyik commented on style.css
>  html {
Kindly follow the design guideline and the color palette provided and change the color of the screenshotted sections below to #ec5242 👍 
<img width="430" alt="Screenshot 2023-04-19 at 9 38 53 PM" src="https://user-images.githubusercontent.com/25887253/233170662-81d90e80-cee3-48ef-8108-ec6bf185b932.png">
<img width="1040" alt="Screenshot 2023-04-19 at 9 39 31 PM" src="https://user-images.githubusercontent.com/25887253/233170670-fcd62fe5-28e4-4480-b8e4-763789a69bb2.png">
<img width="1040" alt="Screenshot 2023-04-19 at 9 39 59 PM" src="https://user-images.githubusercontent.com/25887253/233170675-384116e0-4c00-4107-80de-d658410cc818.png">
<img width="1040" alt="Screenshot 2023-04-19 at 9 40 25 PM" src="https://user-images.githubusercontent.com/25887253/233170683-202db8ee-bf7c-4bf4-9886-46b4e4d2fc3f.png">
<img width="1040" alt="Screenshot 2023-04-19 at 9 40 57 PM" src="https://user-images.githubusercontent.com/25887253/233170690-7c9300f1-3dd7-42e8-83fc-0dda8686c164.png">
<img width="507" alt="Screenshot 2023-04-19 at 9 41 57 PM" src="https://user-images.githubusercontent.com/25887253/233170695-93208d69-f4a4-40ac-81b1-6325985410ca.png">

2023-04-19 19:07 UTC, huseyinbiyik commented on style.css
>  }
Kindly make sure you imported the Lato font. You can check this [page](https://fonts.google.com/specimen/Lato) and use the import method to use the font. Also you can check this [page](https://www.freecodecamp.org/news/how-to-use-google-fonts-in-your-next-web-design-project-e1ad48f1adfa/) to learn how to use a Google font in your project

2023-04-19 19:07 UTC, huseyinbiyik commented on index.html
- [x] Unfortunately, I can't select the correct lines since you didn't follow the Github flow properly. For the card element that I screenshotted below, needs to be a semantic article element instead of div. You did a great job with the nav, header, footer, and sections, so I think you know what I mean with semantic HTML element 👍 
<img width="386" alt="Screenshot 2023-04-19 at 9 53 13 PM" src="https://user-images.githubusercontent.com/25887253/233173135-c64c3037-d778-48df-b9bf-0a813dd53a7a.png">


- [x] Same here, each celebrity card has to be an article tag for semantic reasons. (SEO, accessibility etc)
<img width="446" alt="Screenshot 2023-04-19 at 9 58 35 PM" src="https://user-images.githubusercontent.com/25887253/233173733-e89c628f-48d8-46f5-8ab4-78daf10fc32a.png">

2023-04-20 14:04 UTC, emmiiorji approved these changes
Hi @yashodhicy, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights

- Good job implementing requested changes
- Deployment works properly


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 11:39 UTC, merged